name: Release

on:
  push:
    branches:
      - release
  workflow_dispatch:
    inputs:
      text:
        description: "What changed?"
        required: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Create zip from dist folder
        run: |
          cd dist
          zip -r ../chess-com-insights.zip .

      - name: Get version from package.json
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Create Git tag
        run: git tag v${{ steps.get_version.outputs.version }}

      - name: Push Git tag
        run: git push origin v${{ steps.get_version.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.get_version.outputs.version }}
          tag_name: v${{ steps.get_version.outputs.version }}
          body: |
            Chess.com Insights Release v${{ steps.get_version.outputs.version }}
            <br>
            ${{ github.event.inputs.text }}
          files: |
            chess-com-insights.zip
